spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://moplus-mysql-dev:3306/${DEV_MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # default
      connection-timeout: 3000 # 30 seconds in milliseconds
      keepalive-time: 600000 # 5 minutes in milliseconds

swagger:
  servers:
    - url: https://dev.math-pointer.com
      description: "pointer dev https 서버입니다."
    - url: http://dev.math-pointer.com
      description: "pointer dev http 서버입니다."
    - url: http://localhost:8080
      description: "pointer local 서버입니다."

logging:
  level:
    root: INFO