spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://moplus-mysql-prod:3306/${PROD_MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${PROD_MYSQL_PASSWORD}
    username: ${PROD_MYSQL_USER}
    hikari:
      maximum-pool-size: 10 # default
      connection-timeout: 3000 # 30 seconds in milliseconds
      keepalive-time: 600000 # 5 minutes in milliseconds

swagger:
  servers:
    - url: https://prod.math-pointer.com
      description: "pointer prod https 서버입니다."
    - url: http://prod.math-pointer.com
      description: "pointer prod http 서버입니다."
    - url: http://localhost:8080
      description: "pointer local 서버입니다."

logging:
  level:
    root: INFO