spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: update

swagger:
  servers:
    - url: http://localhost:8080
      description: "pointer local 서버입니다."